name: poke_dex
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  result_dart: ^1.0.5 
  dio: ^5.0.3
  flutter_bloc: ^8.1.2
  flutter_modular: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter  
  mocktail: ^0.3.0
  flutterando_analysis: ^0.0.2

flutter:
  uses-material-design: true

  